var uniliterals = [
  { hiero: ["G1"], translit: "\uA723"},
  { hiero: ["M17"], translit: "\u1EC9"}, // TODO: issue #1.
  { hiero: ["M17","M17"], translit: "y"},
  { hiero: ["D36"], translit: "\uA725"},
  { hiero: ["G43"], translit: "w"},
  { hiero: ["D58"], translit: "b"},
  { hiero: ["Q3"], translit: "p"},
  { hiero: ["I9"], translit: "f"},
  { hiero: ["G17"], translit: "m"},
  { hiero: ["N35"], translit: "n"},
  { hiero: ["D21"], translit: "r"},
  { hiero: ["O4"], translit: "h"},
  { hiero: ["V28"], translit: "\u1E25"},
  { hiero: ["Aa1"], translit: "\u1E2B"},
  { hiero: ["F32"], translit: "\u1E96"},
  { hiero: ["O34"], translit: "s"},
  { hiero: ["S29"], translit: "s"},
  { hiero: ["N37"], translit: "\u0161"},
  { hiero: ["N29"], translit: "\u1E33"},
  { hiero: ["V31"], translit: "k"},
  { hiero: ["W12"], translit: "g"},
  { hiero: ["X1"], translit: "t"},
  { hiero: ["V13"], translit: "\u1E6F"},
  { hiero: ["D46"], translit: "d"},
  { hiero: ["I10"], translit: "\u1E0F"},
];
